import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";

import Header from "@/components/Header";
import { dark } from "@clerk/themes";
import Footer from "@/components/Footer";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

//👇 Import Open Sans font
import { Fredoka } from "next/font/google";

//👇 Configure our font object
const fredoka = Fredoka({
  subsets: ["latin"],
  display: "swap",
});

export default function RootLayout({ children }) {
  return (
    <ClerkProvider
      appearance={{
        baseTheme: dark,
      }}
    >
      <html lang="en" data-theme="lemonade" className={fredoka.className}>
        <body>
          <div className="min-h-screen flex flex-col items-stretch bg-base-200">
            <Header />
            <div className="flex-1 mx-auto w-full min-h-full">{children}</div>
            <Footer />
          </div>
        </body>
      </html>
    </ClerkProvider>
  );
}
